[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
version = "1.0.0"
description = "A maze generator with curses visualization and hex output"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []
license = {text = "MIT"}
authors = [
    {name = "tel-atou", email = "tel-atou@student.1337.ma"},
    {name = "obahya", email = "obahya@student.1337.ma"}
]

[project.optional-dependencies]
dev = [
    "flake8>=6.0.0",
    "mypy>=1.0.0",
]


[tool.setuptools.packages.find]
where = ["."]
include = ["mazegen*"]
